/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import java.awt.Color;

/**
 *
 * @author darta
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private boolean stateBlue = true;
    private boolean stateRed = true;
    private boolean stateGreen = true;
    public NewJFrame() {
        initComponents();
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGreen = new javax.swing.JButton();
        btnRed = new javax.swing.JButton();
        btnBlue = new javax.swing.JButton();
        txtWelcome = new javax.swing.JTextField();
        sldTest = new javax.swing.JSlider();
        btnMix = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGreen.setText("Zaļš");
        btnGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGreenActionPerformed(evt);
            }
        });

        btnRed.setText("Sarkans");
        btnRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedActionPerformed(evt);
            }
        });

        btnBlue.setText("Zils");
        btnBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlueActionPerformed(evt);
            }
        });

        txtWelcome.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtWelcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWelcomeActionPerformed(evt);
            }
        });

        btnMix.setText("MEGABUTTON");
        btnMix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMixActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sldTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGreen)
                        .addGap(11, 11, 11)
                        .addComponent(btnBlue)))
                .addGap(34, 34, 34)
                .addComponent(txtWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtWelcome)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sldTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRed)
                            .addComponent(btnBlue)
                            .addComponent(btnGreen))
                        .addGap(26, 26, 26)
                        .addComponent(btnMix, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(284, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGreenActionPerformed
         if(stateGreen){
            btnGreen.setBackground(Color.green);
            btnGreen.setForeground(Color.red);
        }else{
            btnGreen.setBackground(Color.gray);
            btnGreen.setForeground(Color.white);
        }
        
        stateGreen = !stateGreen;
        coloring();
    }//GEN-LAST:event_btnGreenActionPerformed

    private void btnRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedActionPerformed
 
        if(stateRed){
            btnRed.setBackground(Color.red);
        }else{
            btnRed.setBackground(Color.gray);
        }
        
        stateRed = !stateRed;
        coloring();
        
    }//GEN-LAST:event_btnRedActionPerformed

    
    private void btnBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlueActionPerformed
        txtWelcome.setText("Welcome to the jungle");  
        if(stateBlue){
            btnBlue.setBackground(Color.blue);
        }else{
            btnBlue.setBackground(Color.gray);
        }
        stateBlue = !stateBlue;
        coloring();
 
        
         
    }//GEN-LAST:event_btnBlueActionPerformed

    private void txtWelcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWelcomeActionPerformed
       
    }//GEN-LAST:event_txtWelcomeActionPerformed

    private void btnMixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMixActionPerformed
        btnBlue.setBackground(Color.gray);
        btnRed.setBackground(Color.gray);
        btnGreen.setBackground(Color.gray);
        btnMix.setBackground(Color.gray);
    

    }//GEN-LAST:event_btnMixActionPerformed
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    public void coloring() { 
        
//        int blueInt = (stateBlue)? 1 : 0;
//        int redInt = (stateRed)? 1 : 0;
//        int greenInt = (stateGreen)? 1 : 0;
//        
//        switch (blueInt) {
//            case 1:
//                switch (blueInt) {
//                    case 1:
//                        break;
//                    case 0:
//                        break;
//
//        }
        boolean[] newArray = {stateBlue, stateRed, stateGreen};

        int result = 0;
        for (boolean bit : newArray) {
            result <<= 1;
            if (bit) {
                result += 1;
            }
        }
        
        System.out.println(result);
        switch(result){
            case 1:
                btnMix.setBackground(Color.magenta);
                break;
            case 4:
                btnMix.setBackground(Color.yellow);
                break;
            case 2:
                btnMix.setBackground(Color.cyan);
                break;
            case 3:
                btnMix.setBackground(Color.blue);
                break;
            case 5:
                btnMix.setBackground(Color.red);
                break;
            case 6:
                btnMix.setBackground(Color.green);
                break;
            case 0:
                btnMix.setBackground(Color.white);
                break;
            case 7:
                btnMix.setBackground(Color.gray);
                break;
            default:
          
        }
        
        

                
//        if (!stateBlue && !stateRed && stateGreen) {
//            btnMix.setBackground(Color.magenta);
//        } 
//        if (stateBlue && !stateRed && !stateGreen) {
//            btnMix.setBackground(Color.yellow);
//        } 
//        if (!stateBlue && stateRed && !stateGreen) {
//            btnMix.setBackground(Color.cyan);
//        } 
//         if (!stateBlue && stateRed && stateGreen) {
//            btnMix.setBackground(Color.blue);
//        }  
//        if (stateBlue && !stateRed && stateGreen) {
//            btnMix.setBackground(Color.red);
//        }
//        if (stateBlue && stateRed && !stateGreen) {
//            btnMix.setBackground(Color.green);
//        }
//        if (!stateBlue && !stateRed && !stateGreen) {
//            btnMix.setBackground(Color.white);
//        }
//        if (stateBlue && stateRed && stateGreen) {
//            btnMix.setBackground(Color.gray);
//        }
// Binārā Sjaitīšabas sistēma uztisit pogu ar skaitli 


    }

    private void differentMixStateChange(){
          String result = String.valueOf(stateRed)+ String.valueOf(btnGreen)+String.valueOf(btnBlue) ;  
        }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlue;
    private javax.swing.JButton btnGreen;
    private javax.swing.JButton btnMix;
    private javax.swing.JButton btnRed;
    private javax.swing.JSlider sldTest;
    private javax.swing.JTextField txtWelcome;
    // End of variables declaration//GEN-END:variables
}
